mysql:
      url: "jdbc:mysql://127.0.0.1:3306/sandbox"
      user: "pyspark_user"
      password: "123"
      dbtable: "book_orders"

spark:
      spark_home: 'C:\Users\Georgy\spark\spark-3.1.1-bin-hadoop2.7'
      pyspark_submit_args: "--packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.1 --master local[3] pyspark-shell"
      java_home: 'C:\Program Files\Java\jdk1.8.0_202'

kafka:
      kafka_host: "localhost:9092"
      topic_name: "fake-orders-stream"
      starting_offset: "latest"



